### ISSUE TITLE
APAddressBook framework had been updated. Please fix it, I have not permission.

### ISSUE THREAD

**Issue by Jacenty10** [burczyk/KBContactsSelection#10]
I can't compile current version At my project.
APContact class has no member function "firstName" and "lastName"

KBContactsSelection/KBContactsSelection/APContact+FullName.m:17:14: Property 'firstName' not found on object of type 'APContact *'
KBContactsSelection/KBContactsSelection/APContact+FullName.m:18:23: Property 'firstName' not found on object of type 'APContact *'
KBContactsSelection/KBContactsSelection/APContact+FullName.m:21:14: Property 'lastName' not found on object of type 'APContact *'
KBContactsSelection/KBContactsSelection/APContact+FullName.m:22:68: Property 'lastName' not found on object of type 'APContact *'

It is easy to fix.
Please help me.
Thank you.

to @burczyk

**Comment by burczyk** [comment]
Version `1.2.5` updated today supports APAddressBook `0.2.1` and changed API. It was already pushed to CocoaPods so it should all work again.
