### ISSUE TITLE
Pod install only installs v 1.0.0

### ISSUE THREAD

**Issue by RitvikM** [burczyk/KBContactsSelection#9]
I cant install version 1.2.4 using pods. It says it doesn't exist, and if I try leaving the version out, it gets 1.0.0

**Comment by burczyk** [comment]
Strange situation.
I've just tested it and my Podfile looks like this:

``` ruby
pod 'KBContactsSelection'
```

after runnning `pod install` everything works well:

``` sh
kamil$ pod install
Analyzing dependencies

Downloading dependencies
Installing APAddressBook (0.1.6)
Installing KBContactsSelection (1.2.4)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `KBContactsTest.xcworkspace` for this project from now on.
```

Did you have `KBContactsSelection` installed previously in your project? If so it can be cached and to update it you should explicitly run `pod update` https://guides.cocoapods.org/terminal/commands.html#pod_update.

Let me know if any of these advices help.

**Comment by burczyk** [comment]
Version `1.2.5` updated today supports APAddressBook `0.2.1` and changed API. It was already pushed to CocoaPods so it should all work again.
